# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_id', models.CharField(max_length=8)),
                ('pizza_size', models.CharField(max_length=4)),
                ('costumer_name', models.CharField(max_length=20)),
                ('costumer_address', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
